import os

ALPHA_VANTAGE_BASE_URL = os.environ['ALPHA_VANTAGE_BASE_URL']
ALPHA_VANTAGE_API_KEY = os.environ['ALPHA_VANTAGE_API_KEY']
MONGO_USER = os.environ['MONGO_USER']
MONGO_PASSWORD = os.environ['MONGO_PASSWORD']
MONGO_HOST = os.environ['MONGO_HOST']
MONGO_PORT = 27017


EODHD_API_TOKEN= os.environ['EODHD_API_TOKEN']
EODHD_BASE_URL = os.environ['EODHD_BASE_URL']
